name: zefyr
description: Clean, minimalistic and collaboration-ready rich text editor for Flutter.
version: 1.0.0-dev.2.0
homepage: https://github.com/memspace/zefyr
publish_to: none
environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  collection: ^1.14.6
  url_launcher: ^6.0.9
  quill_delta: ^3.0.0-nullsafety.1
  notus:
    git:
      url: https://github.com/nipunasudha/zefyr
      path: packages/notus
      ref: 1.0-dev
  characters: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.4
